name: angular2
version: 2.0.0-alpha.31
authors:
- 0 <Alex Eagle <alexeagle@google.com>>
- 1 <Chirayu Krishnappa <chirayu@google.com>>
- 2 <Jeff Cross <crossj@google.com>>
- 3 <Matias Niemela <matsko@google.com>>
- 4 <Misko Hevery <misko@google.com>>
- 5 <Rado Kirov <radokirov@google.com>>
- 6 <Tobias Bosch <tbosch@google.com>>
- 7 <Victor Savkin <vsavkin@google.com>>
- 8 <Yegor Jbanov <yjbanov@google.com>>
- 9 <Jeremy Elbourn <jelbourn@google.com>>
description: Angular 2 for Dart - a web framework for modern web apps
homepage: https://github.com/angular/angular
environment:
  sdk: '>=1.10.0-dev.1.10 <2.0.0'
dependencies:
  analyzer: '>=0.24.4 <0.26.0'
  barback: '^0.15.2+2'
  code_transformers: '^0.2.8'
  dart_style: '^0.1.8'
  html: '^0.12.0'
  intl: '^0.12.4'
  logging: '>=0.9.0 <0.12.0'
  source_span: '^1.0.0'
  stack_trace: '^1.1.1'
  quiver: '^0.21.4'
dev_dependencies:
  guinness: '^0.1.17'
transformers:
- angular2
- $dart2js:
    commandLineOptions:
    - --show-package-warnings
